apiVersion: apps/v1
kind: Deployment
metadata:
  name: gyani-bot
spec:
  selector:
    matchLabels:
      app: gyani-bot
  template:
    metadata:
      labels:
        app: gyani-bot
    spec:
      containers:
      - name: gyani-bot
        image: gyanichatbotacireg.azurecr.io/mybot:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 5050
